services:
  web:
    build: . #現在のディレクトリのDockerfileを指定
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    environment:
      TZ: Asia/Tokyo
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
    ports:
      - "3000:3000"
    depends_on: #先にdbから起動させる
      - db
    tty: true
    stdin_open: true

  chrome:
    image: seleniarm/standalone-chromium:latest
    shm_size: 256m
    ports:
      - 4444:4444

  db:
    image: postgres:16
    volumes:
      - db-store:/var/lib/postgresql/data # データを永続化するための設定
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: 'Asia/Tokyo'
    ports:
      - "5432:5432"
    restart: always

volumes:
  db-store: